name: graphql_client_generator
description: The GraphQL client generator.
version: 0.0.1
homepage: https://github.com/dart-graphql/graphql_client
authors:
  - Thomas Hourlier <hourliert@gmail.com>
  - TruongSinh Tran-Nguyen <i@truongsinh.pro>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  logging: ^0.11.3

dev_dependencies:
  test: ^1.5.3
  perfectionist: ^2.0.0
