name: graphql_client_generator
description: The GraphQL client generator.
version: 0.0.1
homepage: https://github.com/dart-graphql/graphql_client
authors:
  - Thomas Hourlier <hourliert@gmail.com>
  - TruongSinh Tran-Nguyen <i@truongsinh.pro>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  logging: ^0.11.3
  build: ^0.10.0
  barback: ^0.15.2
  build_barback: ^0.4.0
  code_builder: ^2.0.0-alpha+1
  dart_style: ^1.0.7
  graphql_parser: ^1.0.0
  path: ^1.4.2

dev_dependencies:
  test: ^1.5.3
  perfectionist: ^2.0.0
